#                                                                        #
# Settings                                                               #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Just add your own modifications as necessary.                          #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

TYPO3:
  FLOW3:
    security:
      authentication:
        providers:
          Typo3SetupProvider:
            provider: 'FileBasedSimpleKeyProvider'
            providerOptions:
              keyName: 'SetupKey'
            requestPatterns:
              controllerObjectName: "TYPO3\Setup\Controller\.*"
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: 'setup/login'

  Setup:
    initialPasswordFile: '%FLOW3_PATH_DATA%SetupPassword.txt'
    stepOrder: ['database', 'final']
    steps:
      database:
        className: 'TYPO3\Setup\Step\DatabaseStep'
        requiredConditions:
          - className: 'TYPO3\Setup\Condition\PdoDriverCondition'
      final:
        className: 'TYPO3\Setup\Step\FinalStep'

  Form:
    presets:
      'typo3.setup':
        title: 'Setup Elements'
        parentPreset: 'default'
        formElementTypes:
          'TYPO3.Form:Form':
            renderingOptions:
              templatePathPattern: 'resource://TYPO3.Setup/Private/Form/{@type}.html'
          'TYPO3.Setup:LinkElement':
            superTypes: ['TYPO3.Form:ReadOnlyFormElement']
            properties:
              text: ''
              class: 'btn'
              href: ''
          'TYPO3.Setup:DatabaseSelector':
            superTypes: ['TYPO3.Form:FormElement']
